### ISSUE TITLE
シェープファイルを読み込んで属性値を利用する機能

### ISSUE THREAD

**Issue by m1saito** [crest-cassia/CrowdWalk#179]
東京電機大学の荻野さんから送られてくる北千住マップの安全度・危険度データは、シェープファイルのLineデータの属性値になっているため、CrowdWalkで利用するためには読み取り用の新たな仕組みが必要である。
CrowdWalkがシェープファイルを読み込んで、任意の属性値をMapLinkのadditionalDataとして利用できるようにする機能を作る。

シェープファイルの危険度・安全度データ：
- 危険度 - 属性名：Danger1, 値：0.000000～1.000000
- 安全度 - 属性名：Safety, 値：0.000000～1.000000

CrowdWalkがシェープファイルを読み込む際に、利用する属性に関する情報が必要になる。これは別ファイルに定義する。

属性定義ファイルの書式：

```
    {
        "Link" : {
            "属性名" : "型(Boolean/Integer/Long/Double/String)"
         }
    }
```

実際の属性定義(ファイル名は"additionalDataSpecs.json"等)：

```
    {
        "Link" : {
            "Danger1" : "Double",
            "Safety" : "Double"
        }
    }
```

CrowdWalkが属性値にアクセスするためのメソッド：

```
    public boolean hasAdditionalData()
    public Object getAdditionalData(String name)
    public int getAdditionalDataInt(String name)
    public double getAdditionalDataDouble(String name)
    public String getAdditionalDataString(String name)
```

MapLinkクラスのメソッドとして定義する。
CrowdWalkWrapperのサブクラスでの使用を想定。

**Comment by noda50** [comment]
シェープファイルの扱いですが、
SHP → JOSM (OSM 用のエディタ) → GeoJSON 形式で出力　
としたほうがやりやすいかもしれません。

**Comment by m1saito** [comment]
山下先生が研究から離れている間に電機大の荻野さんとの連絡も途絶えたため、ペンディング状態になっていました。
開発はほぼ終了しており、ご指摘の通り GeoJSON 形式に変換したファイルを CrowdWalk で読み込む様になっています。
山下先生からも完成させておくように言われているので、折を見て commit しておきます。

**Comment by noda50** [comment]
これは、GeoJSON を直接 CrowdWalk が読み込める、という機能でしょうか？

**Comment by m1saito** [comment]
はい、そうです。
読み込ませる GeoJSON ファイルは ogr2ogr というフリーのツールを使って事前に作成します。

**Comment by m1saito** [comment]
この機能は設計があまりよくないので中止とします。
MapLinkではなくOBNodeに属性データを持たせる方が汎用的で用途が広がります。
