### ISSUE TITLE
log_individual_pedestrians_initial.csv

### ISSUE THREAD

**Issue by noda50** [crest-cassia/CrowdWalk#187]
このログ形式は、何のために存在するのか？

"initial" といいながら、終了時に出力しているので、どうみても、各エージェントの最終状態。

形式が固定なので、拡張に非常に向かない。

使いみちによっては残すが、現状では意味不明のログ。

**Comment by t-ymst** [comment]
大西さんのRAで使用していると思われる方もいたのですが、現在では使用していないことが確認できたため、削除いたします。

**Comment by noda50** [comment]
削除するのは誰？

**Comment by tkmnet** [comment]
https://github.com/crest-cassia/CrowdWalk/commit/1ecb47e23fdead2e86be14ce3e323c168f4a98a0
