### ISSUE TITLE
ネット環境無しでの build

### ISSUE THREAD

**Issue by noda50** [crest-cassia/CrowdWalk#207]
現在、ネットに繋がっていない状態での build ができない。

gradle で、利用しているライブラリのバージョンチェックをするためなのか、オフライン状態で build すると、失敗する。

移動中にデバッグする際など不便なので、できれば、オフラインではチェックしないとか、あるいはオプションで、ライブラリのバージョンチェックをしないとかにできないか？

**Comment by m1saito** [comment]
```
gradle --offline
```
で出来るようです。

**Comment by noda50** [comment]
ありがとうございます。
gradle の機能であったか。
