### ISSUE TITLE
新しい GUI で、ruby generator の場合に表示でエラーが起きる。

### ISSUE THREAD

**Issue by noda50** [crest-cassia/CrowdWalk#209]
新しい GUI において、ruby による generation rule を使うと、エラーが生じる。
[aaa.log](https://github.com/crest-cassia/CrowdWalk/files/1327446/aaa.log)

**Comment by noda50** [comment]
エラーが起きるサンプルは、

sample/generatedTown/gridTown02.prop.json

**Comment by m1saito** [comment]
130f28c にて修正完了しました。

**Comment by noda50** [comment]
動作確認しました。
ありがとうございます。
