### ISSUE TITLE
Dump, None, Pause event

### ISSUE THREAD

**Issue by noda50** [crest-cassia/CrowdWalk#211]
シミュレーションの途中で発生するイベントで、以下のものを追加。
- Dump Event: エージェントの状態を、generation rule の形で dump する。restart 機能実装のための拡張。
- Null Event: なにもしないイベント。コメント用。
- Pause Event: GUIモードの時、ある時刻で一旦とめる。

**Comment by noda50** [comment]
Null Event は完了。
9b20948f75f36004146775d8cc247eea028125d4

**Comment by noda50** [comment]
Dump Event も、基本的なところは完了。
ただし、残っている生成ルールのチェックと、動作の確認がまだ。
特に、再スタートの場合のエージェントの動作が正しいかどうか。
80522fe2bdc4fcc63683b249e8b1bd78ea972fa4

**Comment by noda50** [comment]
Pause Event の実装。
止めることはできた。
ただし、画面の表示の変更ができない。
これは斎藤さんにお願いできるか？
b02745417cae9f9813633a2f8a0b24ea6f00deb6

**Comment by noda50** [comment]
現状、Pause Event で、シミュレーションを一旦中断するのは、
PauseEvent から、 <getScenario().getSimulationLauncher().pause()> でやっている。
しかし、画面表示の変更は、SimulationFrame3D/2D の中の start_button に埋め込まれているので、外部から呼び出せない。

**Comment by noda50** [comment]
PauseEvent で、画面の制御をうまく連動させるため、まずは、pause メソッドの定義場所を変更。
もともと、GuiSimulationLauncherで定義されていたが、BasicSimulationLauncherに移動。GuiSimulationLauncher でOverride。
将来的には、2D, 3D Launcher のところで、適切な画面制御を組み合わせる。

7058e1894d2e4eac7e393c7911aac81ba3db36ee

**Comment by m1saito** [comment]
スタートボタンの連動が完了しました。
6b17e75
シミュレーションビューアのソース修正を避けるため、BasicSimulationLauncher の pause() は pauseRequest() に変更させて頂きました。
