### ISSUE TITLE
画面の色の反転

### ISSUE THREAD

**Issue by noda50** [crest-cassia/CrowdWalk#212]
シミュレーション画面の色を反転（バックを黒地とする）ことはできたのでしたっけ？

昔のデモ映像で、そういうのがあった（小倉駅でのガス拡散）のですが、あれは、特注でしたでしょうか？それとも、スイッチひとつ？

野田

**Comment by m1saito** [comment]
2Dシミュレーションビューアは白に固定ですが、3Dシミュレーションビューアならばプロパティーファイルで

"background_color": "black",

とすれば黒に変えられます。

**Comment by noda50** [comment]
なるほど、ありがとうございます。
