### ISSUE TITLE
internet offline mode

### ISSUE THREAD

**Issue by noda50** [crest-cassia/CrowdWalk#213]
現状、internet が使えないと、GSI へアクセスに行こうとして、時間が無駄に撮られる現象が起きている。
ネットワークはつながっているが、internet 接続になっていない場合、GSI のデータを取得に行って、フェイルするまで戻ってこない、という現象が出る。

オプションで、オフラインモードにできないか？

**Comment by m1saito** [comment]
現在の作業が終了したら対応します。


なお手軽に出来る対応策として、cacheディレクトリのデータがどこかにあれば

それを丸ごとコピーすればInternetにアクセスしなくなります。

**Comment by m1saito** [comment]
更に簡単な対応策として、マップファイル及びプロパティファイルの zone を 0 にすればアクセスしなくなります。

**Comment by m1saito** [comment]
オフラインモードの追加が完了しました。
