### ISSUE TITLE
2015年10月当時の設定ファイル群が実行できない

### ISSUE THREAD

**Issue by t-ymst** [crest-cassia/CrowdWalk#215]
2015年10月にcrowdwalk で稼働していた設定ファイルを最新版(2018年7月20日)で稼働させたところ、下記のエラーメッセージが出て終了してしまうという現象が見られたため、ご対応をお願いいたします。
設定ファイル群は現状でも研究要素があり公開しない方がよいと思われますので、斎藤さん・野田さんにメールにてお送りさせていただきます。
ご対応をお願いいたします。

-----------------------------------------------------

.................中略.................

ITK_Warn[?????]:@ nodagumi.ananPJ.NetworkMap.Node.MapNode.getHint(MapNode.java:311)
ITK_Warn[No hint for goal]:toward tag ROOT_5F_R06 from node 1290432569 in mode (null) .
ITK_Warn[?????]:@ nodagumi.ananPJ.NetworkMap.Node.MapNode.getHint(MapNode.java:311)
ITK_Warn[No hint for goal]:toward tag ROOT_5F_R06 from node 1290612410 in mode (null) .

.................中略.................

ITK_Info:auto simulation start
ITK_Debug[Cycle]:at: 18:01:40 (100) time: 23:42:36.884 walking: 1806
ITK_Debug[Cycle]:at: 18:03:20 (200) time: 23:42:39.444 walking: 1806
ITK_Debug[Cycle]:at: 18:05:00 (300) time: 23:42:41.911 walking: 1806
ITK_Debug[Cycle]:at: 18:06:40 (400) time: 23:42:44.217 walking: 1806
ITK_Debug[Cycle]:at: 18:08:20 (500) time: 23:42:46.394 walking: 1806
ITK_Debug[Cycle]:at: 18:10:00 (600) time: 23:42:48.546 walking: 1806
ITK_Error[!!!!!]:@ nodagumi.ananPJ.NetworkMap.Node.MapNode.getHint(MapNode.java:304)
ITK_Fatal[No hint for goal]:toward tag DENSITY from node 515501038 in mode (null) .
ITK     :nodagumi.ananPJ.NetworkMap.Node.MapNode.getHint(MapNode.java:308)
ITK     :nodagumi.ananPJ.NetworkMap.Node.MapNode.getDistance(MapNode.java:353)
ITK     :nodagumi.ananPJ.Agents.WalkAgent.calcCostFromNodeViaLink(WalkAgent.java:1307)
ITK     :nodagumi.ananPJ.Agents.NaiveAgent.calcCostFromNodeViaLink(NaiveAgent.java:167)
ITK     :nodagumi.ananPJ.Agents.WalkAgent.chooseNextLinkBody(WalkAgent.java:1204)
ITK     :nodagumi.ananPJ.Agents.WalkAgent.accumulateSocialForces(WalkAgent.java:908)
ITK     :nodagumi.ananPJ.Agents.WalkAgent.calcAccel(WalkAgent.java:784)
ITK     :nodagumi.ananPJ.Agents.WalkAgent.calcSpeedBody(WalkAgent.java:742)
ITK     :nodagumi.ananPJ.Agents.WalkAgent.calcSpeed(WalkAgent.java:653)
ITK     :nodagumi.ananPJ.Agents.WalkAgent.updateSpeed(WalkAgent.java:475)
ITK     :nodagumi.ananPJ.Agents.WalkAgent.preUpdate(WalkAgent.java:464)
ITK     :nodagumi.ananPJ.Agents.AwaitAgent.preUpdate(AwaitAgent.java:208)
ITK     :nodagumi.ananPJ.Simulator.AgentHandler.preUpdateAgentsOnLink(AgentHandler.java:985)
ITK     :nodagumi.ananPJ.Simulator.AgentHandler.preUpdateAgents(AgentHandler.java:919)
ITK     :nodagumi.ananPJ.Simulator.AgentHandler.update(AgentHandler.java:999)
ITK     :nodagumi.ananPJ.Simulator.EvacuationSimulator.updateEveryTick(EvacuationSimulator.java:949)
ITK     :nodagumi.ananPJ.BasicSimulationLauncher.simulateOneStepBare(BasicSimulationLauncher.java:365)
ITK     :nodagumi.ananPJ.BasicSimulationLauncher.simulateMainLoop(BasicSimulationLauncher.java:393)
ITK     :nodagumi.ananPJ.GuiSimulationLauncher$2.run(GuiSimulationLauncher.java:225)
ITK     :java.lang.Thread.run(Unknown Source)
ITK_Info[Save Settings File]:GuiSimulationLauncher.ini

**Comment by m1saito** [comment]
解決済みのため終了。
