### ISSUE TITLE
NoClassDefFoundError: javafx/embed/swing/JFXPanel

### ISSUE THREAD

**Issue by noda50** [crest-cassia/CrowdWalk#220]
斎藤さん、

CrowdWalk の利用者から、以下の報告がありました。
何が原因かわかりますか？

> 最新のCrowdWalkをGitHubからダウンロードし、
> 卒業研究を再開しようとしたところ、
> 以下のようなエラーがでてしまいました。
> 
> 
> maruken@maruken-Inspiron-580:~/デスクトップ/インターンシップ/CrowdWalk/crowdwalk$ sh quickstart.sh 
> java -Dfile.encoding=UTF-8 -jar ./build/libs/crowdwalk.jar 
> Exception in thread "main" java.lang.NoClassDefFoundError: javafx/embed/swing/JFXPanel
>     at nodagumi.ananPJ.Editor.MapEditor.<init>(MapEditor.java:154)
>     at nodagumi.ananPJ.CrowdWalkLauncher.launchMapEditor(CrowdWalkLauncher.java:209)
>     at nodagumi.ananPJ.CrowdWalkLauncher.parseCommandLine(CrowdWalkLauncher.java:135)
>     at nodagumi.ananPJ.CrowdWalkLauncher.main(CrowdWalkLauncher.java:281)
> Caused by: java.lang.ClassNotFoundException: javafx.embed.swing.JFXPanel
>     at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
>     at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
>     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
>     ... 4 more

**Comment by m1saito** [comment]
JavaFX のクラスが見つからないというエラーが出ています。

調査したところ、Oracle 版の最新の JDK 11 から JavaFX が同梱されなくなった模様です。
また、JavaFX を別途インストールしても現在の quickstart.sh では設定が足りないため動かないと思います。

JDK 11 をアンインストールして、Oracle 版 JDK 8 をインストールすれば動くと思います。

**Comment by noda50** [comment]
斎藤さん、
調査、ありがとうございます。

津谷さん、これで解決するかな？

**Comment by noda50** [comment]
斎藤さん、

今後のことを考えると、長期的にはどうしておくのがいいか、分かるでしょうか？

JavaFX を使わないようにする？
JavaFX を別途インストールして、quickstart.sh でうまく環境設定する？
JDK-8を使い続ける？

**Comment by m1saito** [comment]
JDK 11 への対応が完了しました。
動作確認は Windows7 上でしかおこなっていませんが多分大丈夫です。
また JDK インストール手順のドキュメントも合わせて修正しておきました。
