### ISSUE TITLE
RubyAgent から ChooseNextLinkCache をクリアできるようにする。

### ISSUE THREAD

**Issue by noda50** [crest-cassia/CrowdWalk#223]
RubyAgent  の cycleThink などで ゴールやリンクの距離などを変更した際に、直前の ChooseNextLinkCache を間違って参照しないように、明示的にクリアする方法を用意する。

**Comment by tkmnet** [comment]
https://github.com/crest-cassia/CrowdWalk/commit/a9946d09ed80a4f5268544507e674c1af9574afa
