### ISSUE TITLE
ubuntu 20.04  で動かない問題。

### ISSUE THREAD

**Issue by noda50** [crest-cassia/CrowdWalk#224]
java 関係で、 ubuntu-20.04 で動かない問題のまとめ

- java-16 問題
-- java-16 では、gradle がうまく動かない(最新版用の gradle ファイルにできていない）ため、build のためには、java-14 以下でないといけない。
- javafx 問題
-- ubuntu の javafx ではクラッシュする。 javafx を消すか、もしくは参照しないようにしないといけない。

いずれも情報源・まとめは、
[鷹見くんのページ](https://github-wiki-see.page/m/crest-cassia/CrowdWalk/wiki/%E6%97%A2%E7%9F%A5%E3%81%AE%E3%83%88%E3%83%A9%E3%83%96%E3%83%AB%E3%81%A8%E3%83%88%E3%83%A9%E3%83%96%E3%83%AB%E3%82%B7%E3%83%A5%E3%83%BC%E3%83%88)

**Comment by noda50** [comment]
java-16 問題は、コンパイルで gradle 動かすときだけ java-11 にする方法で、回避できた。
`JAVA_HOME=<java-11 の home> ./gradlew｀
でいけた。
ubuntu では、java の home 群は、 /usr/lib/jvm の下にある。

**Comment by noda50** [comment]
javafx 問題は、
 ` /usr/lib/x86_64-linux-gnu/jni/libjfxwebkit.so`
が元凶と思われる。
これをロードさせない方法がわからない。 mv しておけば大丈夫だが。

jfx を全部外すと、josm が動かないという問題が発生する。依存関係があるらしい。

**Comment by tkmnet** [comment]
Java-16以上でビルドできない問題と，JFXがセグフォで落ちる問題に対処してみました．
一応，手元の現象を再現できていた環境で動くようになりましたが，大丈夫そうでしょうか？

**Comment by tkmnet** [comment]
ただJava16からプリミティブ値系のクラスのコンストラクタの非推奨警告が出るようになりました（非推奨はJava9から）が，その対応は今のところまだしていません．

~~`new Double(1.0)`~~ --> Double.valueOf(1.0)

**Comment by tkmnet** [comment]
JavaFXのバージョンを11に戻したところ，JavaFXのGradleプラグインを使わなかった時と同様にセグフォが発生した．
したがって，バージョンを11に問題があったと判断した．
