### ISSUE TITLE
Modeの一覧を表示させる方法について

### ISSUE THREAD

**Issue by F22vsYF23** [crest-cassia/CrowdWalk#226]
(1)
<img width="960" alt="未完成" src="https://github.com/crest-cassia/CrowdWalk/assets/153685915/14c9dc52-73f3-43dc-a946-a09ed987c199">

(2)
https://user-images.githubusercontent.com/6541505/42926501-9596e7c8-8b6c-11e8-82f5-df720f73797c.png

初心者です。すみません、(1)を(2)のようにmodeの一覧を表示させたいのですが、どうすればいいのでしょうか?
アドバイスよろしくお願い致します。

**Comment by tkmnet** [comment]
どのような環境で実行していますでしょうか？

**Comment by tkmnet** [comment]
もしWindows上でquickstart.batを使って起動している場合であれば，
4Kディスプレイなどを使っていて，
ディスプレイのスケール設定を200%などに設定していることで問題が起こっている可能性が考えられます．

この場合，
・ウインドウの右下を引っ張ってウインドウを大きくするか，
・ウインドウを最大化するか，
・スケール設定を100%にするか
で対応できるかと思います．

**Comment by F22vsYF23** [comment]
解決いたしました。ありがとうございます。すみません。更に新しい問題が発生してしまいました…
すみません、卒業研究にてCrowdwalkでシミュレーションをしたいのですが、トラブルが発生してしまい、途中で行き詰っています。
まず、私はCrowdwalkのチュートリアルのマップファイルの作成にまで手を付けていました。しかし、そこで、Crowdwalkのチュートリアルで勧められていたOracle版のJDK8をインストールしましたが、それを間違って更新してしまって焦った事により、なんとかしようと間違ってCrowdwalkのチュートリアルにあるコマンド、export LANG=ja_JP.UTF-8
export JAVA_OPTS='-Dgroovy.source.encoding=UTF-8 -Dfile.encoding=UTF-8' をGit BashのCrowdWalk の作業ディレクトリに移動した状態で打ち込んでしまい、sh quickstart.sh のコマンドをgit bashのCrowdWalk の作業ディレクトリに移動した状態で打ち込んでもマップエディタが出てこなくなり、送信した画像(1)のようになってしまいます。Network Map Editorを開くにはどうすればよいのでしょうか?....大変申し訳ございませんが、御解答の程よろしくお願い致します。

①スクリーンショット 2024-01-11 104029

CrowdwalkチュートリアルのURL→ https://github.com/crest-cassia/CrowdWalk/wiki/CrowdWalk-%E3%83%81%E3%83%A5%E3%83%BC%E3%83%88%E3%83%AA%E3%82%A2%E3%83%AB

**Comment by tkmnet** [comment]
#227

**Comment by tkmnet** [comment]
（追加対応）
WindowsでのHiDPIスケーリング機能を無効化
https://github.com/crest-cassia/CrowdWalk/commit/dee0007e093cc0658b38ae8f9af8ab10b5b5fc85
