### ISSUE TITLE
Network Map Editorが開かない

### ISSUE THREAD

**Issue by F22vsYF23** [crest-cassia/CrowdWalk#227]
すみません、卒業研究にてCrowdwalkでシミュレーションをしたいのですが、トラブルが発生してしまい、途中で行き詰っています。
まず、私はCrowdwalkのチュートリアルのマップファイルの作成にまで手を付けていました。しかし、そこで、Crowdwalkのチュートリアルで勧められていたOracle版のJDK8をインストールしましたが、それを間違って更新してしまって焦った事により、なんとかしようと間違ってCrowdwalkのチュートリアルにあるコマンド、export LANG=ja_JP.UTF-8
export JAVA_OPTS='-Dgroovy.source.encoding=UTF-8 -Dfile.encoding=UTF-8' をGit BashのCrowdWalk の作業ディレクトリに移動した状態で打ち込んでしまい、sh quickstart.sh のコマンドをgit bashのCrowdWalk の作業ディレクトリに移動した状態で打ち込んでもマップエディタが出てこなくなり、送信した画像(1)のようになってしまいます。Network Map Editorを開くにはどうすればよいのでしょうか?....大変申し訳ございませんが、御解答の程よろしくお願い致します。

①
![image](https://github.com/crest-cassia/CrowdWalk/assets/153685915/c1880a95-2a0f-4819-862f-5ce235d28ede)

CrowdwalkチュートリアルのURL→ https://github.com/crest-cassia/CrowdWalk/wiki/CrowdWalk-%E3%83%81%E3%83%A5%E3%83%BC%E3%83%88%E3%83%AA%E3%82%A2%E3%83%AB

**Comment by tkmnet** [comment]
`export ...` の操作によって不具合が起こっているわけでないと思います．
画面の出力は本当にそれだけですか？
`Error: Unable to access jarfile ...`や`bash: java: command not found`のような出力が続いていないでしょうか？

`Error: Unable to access jarfile ...`なら，
`./gradlew.bat build`を先に実行してください．

`bash: java: ...`なら，
Javaのインストール手順が終わっていません．（PATHにJavaが入っていない）

**Comment by tkmnet** [comment]
また，JDKはOracleJDK 18でも問題ありません．
OracleJDK 18は，`winget install Oracle.JDK.18` で入ります．

**Comment by F22vsYF23** [comment]
すみません。御返信ありがとうございます。画像のままです。[Error: Unable to access jarfile ...bash: java: command not found]のような表示は出ません…一旦指摘された事をやってみます。ありがとうございます。

**Comment by tkmnet** [comment]
ちなみに，その後ろはプロンプト（$ ）が返ってきているのでしょうか？
それとも固まった状態なのでしょうか？

**Comment by F22vsYF23** [comment]
戻ってきてます。固まっていません。
すみません、ご指摘されたとおりに作業を行った所、変な表示が出てきました。
<img width="727" alt="スクリーンショット 2024-01-14 202546" src="https://github.com/crest-cassia/CrowdWalk/assets/153685915/4580005d-7161-49f6-ac77-a5ddcf564aba">

**Comment by tkmnet** [comment]
`java -version` の出力を貼っていただけますか？

**Comment by tkmnet** [comment]
どのような設定で動かしているか，こちらからはよくわからないのでとりあえず以下の操作は確認してください．

1. 再起動（Gradleのバックグラウンド処理を止めるため．再起動しない方法もあるが理解して操作する必要があるので）
2. `winget install Oracle.JDK.18`
3. 再起動（PATHの再読み込みをするため．再起動しない方法もあるが理解して操作する必要があるので）
4. `java -version`が以下の出力に一致することを確認
```
java version "18.0.2.1" 2022-08-18
Java(TM) SE Runtime Environment (build 18.0.2.1+1-1)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.2.1+1-1, mixed mode, sharing)
```
5. `sh ./gradlew clean`
6. `sh ./gradlew build`
7. `sh ./quickstart.sh`

**Comment by F22vsYF23** [comment]
ありがとうございます。やってみます。

**Comment by F22vsYF23** [comment]
やってみましたが、javaのバージョンは一緒でした（①）。しかし再度同じような出力が出てしまいました（②）。
①
<img width="542" alt="スクリーンショット 2024-01-14 210332" src="https://github.com/crest-cassia/CrowdWalk/assets/153685915/6457d3ec-4a19-4cd4-8e57-c6611503ada1">

②
<img width="727" alt="スクリーンショット 2024-01-14 202546" src="https://github.com/crest-cassia/CrowdWalk/assets/153685915/b4ae4cab-b69f-43c0-9889-94324b0c35c5">

**Comment by tkmnet** [comment]
一度，`C:\Users\<USER>\.gradle` を削除して，
`sh ./gradlew clean; sh ./gradlew build` してもらえますか？

また，もしかしたら`export`で表示される内容を見ればわかるかもしれません．

**Comment by F22vsYF23** [comment]
<img width="817" alt="スクリーンショット 2024-01-19 094927" src="https://github.com/crest-cassia/CrowdWalk/assets/153685915/13c9ebcb-24d9-4d91-9dbd-e67008dbd5ba">
<img width="858" alt="スクリーンショット 2024-01-19 095022" src="https://github.com/crest-cassia/CrowdWalk/assets/153685915/72433130-b438-4fda-91a8-f939eaaa89c2">
<img width="857" alt="スクリーンショット 2024-01-19 095049" src="https://github.com/crest-cassia/CrowdWalk/assets/153685915/34ba98d1-222f-4ef6-a03e-42adbcaa4184">
<img width="423" alt="スクリーンショット 2024-01-19 095104" src="https://github.com/crest-cassia/CrowdWalk/assets/153685915/465a080c-f250-4e24-bf56-2cc47c46ae05">

すみません、内容を張り付けました。御確認の程、よろしくお願い致します。

**Comment by tkmnet** [comment]
1枚目の下から7行目の `JAVA_HOME` が設定されていることが気になります．
Java 8を入れるときにどこかで設定したかと思いますが，こちらの設定を消してみてください．

**Comment by tkmnet** [comment]
1. 消した後に再起動
2. exportしてJAVA_HOMEが消えたことを確認
3. sh ./gradlew clean
4. sh ./gradlew build
5. sh ./quickstart.sh

**Comment by F22vsYF23** [comment]
すみません、どうやって消せば良いですか？

**Comment by tkmnet** [comment]
Java8をインストールする作業をしたときに，システムプロパティで設定していませんか？

**Comment by F22vsYF23** [comment]
環境変数の事ですか?

**Comment by F22vsYF23** [comment]
<img width="960" alt="image" src="https://github.com/crest-cassia/CrowdWalk/assets/153685915/69da70d9-b6ab-4031-a3c6-0b978d5fbbb8">
すみません、図は出たのですが、編集するためのmodeが表示されません…

**Comment by tkmnet** [comment]
右下を引っ張っても出てこないでしょうか？
出てこないのであれば，デスクトップを右クリック，ディスプレイ設定？，スケール？を100%に設定してください．

**Comment by F22vsYF23** [comment]
![image](https://github.com/crest-cassia/CrowdWalk/assets/153685915/5004c9fd-f6f4-439f-b096-95c6afc22358)
![image](https://github.com/crest-cassia/CrowdWalk/assets/153685915/f995685b-2da1-48db-b68b-85975b862678)
すみません、このように拡大率100%にしても出てきません...

**Comment by tkmnet** [comment]
なるほど．ありがとうございます．状況がある程度わかりました．
```
 rm GuiSimulationLauncher.ini
```
で`GuiSimulationLauncher.ini`を削除してみてください．

**Comment by tkmnet** [comment]
もし解決しなければ，以下のファイルを更新しましたので，それを使って起動してください．
（この時，GuiSimulationLauncher.iniも削除してから試してください）
https://raw.githubusercontent.com/crest-cassia/CrowdWalk/master/crowdwalk/quickstart.bat

**Comment by F22vsYF23** [comment]
すみません、解決いたしました。ありがとうございます。大変助かりました。わざわざありがとうございます。しかし、新たにBackground Imageで背景画像を取り込もうとしたところ、警告マークが出てきてしまいました。すみません、これは私のインストールの過程に何か間違いがある感じなのですか？
教えてもらえたら嬉しいです。よろしくお願い致します。
![スクリーンショット 2024-01-19 192912](https://github.com/crest-cassia/CrowdWalk/assets/153685915/db09ebbc-1193-4530-98da-38a5c75189e2)

**Comment by tkmnet** [comment]
先にFile->Save map asからマップのファイルを保存して，保存した同じフォルダの中に直接画像ファイルを置いてください．
マップファイルと同じフォルダにある画像のみ読み込むことができます．

**Comment by tkmnet** [comment]
[チュートリアル中の記述](https://github.com/crest-cassia/CrowdWalk/wiki/CrowdWalk-%E3%83%81%E3%83%A5%E3%83%BC%E3%83%88%E3%83%AA%E3%82%A2%E3%83%AB#:~:text=%E3%81%93%E3%81%93%E3%81%A7%E4%B8%80%E6%97%A6%E3%82%BB%E3%83%BC%E3%83%96%E3%81%97%E3%81%A6%E3%83%9E%E3%83%83%E3%83%97%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%92%E4%BD%9C%E6%88%90%E3%81%97%E3%81%BE%E3%81%99%E3%80%82%E3%83%9E%E3%83%83%E3%83%97%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%8C%E5%AD%98%E5%9C%A8%E3%81%97%E3%81%A6%E3%81%84%E3%81%AA%E3%81%84%E3%81%A8%E6%AC%A1%E3%81%AE%E6%89%8B%E9%A0%86%E3%81%A7%E3%81%8A%E3%81%93%E3%81%AA%E3%81%86%E8%83%8C%E6%99%AF%E7%94%BB%E5%83%8F%E3%81%AE%E3%82%BB%E3%83%83%E3%83%88%E6%A9%9F%E8%83%BD%E3%81%8C%E4%BD%BF%E3%81%88%E3%81%AA%E3%81%84%E3%81%9F%E3%82%81%E3%81%A7%E3%81%99%E3%80%82)

**Comment by tkmnet** [comment]
本件，もし解決していましたら，Closeをお願いします．
